ARG NODE_VERSION=node:20.19.0

FROM $NODE_VERSION-alpine3.20 AS production

RUN apk add g++ make py3-pip
RUN npm install -g pnpm@10.9.0

ENV HOST=0.0.0.0
ENV DIR=/usr/src/app

# Service hostname
ENV NUXT_HOST=0.0.0.0

# Service version
ARG NUXT_APP_VERSION
ENV NUXT_APP_VERSION=${NUXT_APP_VERSION}

# Build variable
ARG GOOGLE_SHEETS_ID=1GJYgrLMOROAH7K8Jb-X8As9SXhPjayRy2W1xe9ca704
ARG GOOGLE_SHEETS_RANGE=data-uat!A1:Z1000
ARG GOOGLE_CLIENT_ID=49742298105-57hlkd99vmeljkm8694ldnne502peu59.apps.googleusercontent.com
ARG GOOLE_API_KEY=AIzaSyAR9eDDji5FBR3RlK4fGkap8MnqQoAvNik
ARG CONTENT_URL=https://scontent-uat.finnomena.com
ARG HEADER_VERSION=latest
ARG FINNOMENA_API_URL=https://api-uat.finnomena.com
ARG FINNOMENA_WEBSITE_URL=https://uat.finnomena.com

# Run in production mode
ENV NODE_ENV=production

# create destination directory
WORKDIR $DIR

# Bundle app source
COPY . .

RUN rm -rf node_modules && pnpm install --no-frozen-lockfile
RUN pnpm build


ENTRYPOINT ["node", ".output/server/index.mjs"]
